#
# description: Archivo de configuracion de la lambda usuarios
# author: Rafael Cetina
# creationDate: 13 de Diciembre del 2021
#
get-usuarios:
  handler: src/lambdas/usuarios/handler.getData
  name: ${self:service}-${self:provider.stage}-client-get-usuarios
  description: Método que obtiene los usuarios registrados.
  tags: ${self:custom.environment.LAMBDA_TAGS_LIST}
  events:
    - http:
        path: api/usuarios
        method: get
        cors: true
get-usuario-by-id:
  handler: src/lambdas/usuarios/handler.getDataById
  name: ${self:service}-${self:provider.stage}-client-get-usuario-by-id
  description: Método que obtiene un usuario dado un id.
  tags: ${self:custom.environment.LAMBDA_TAGS_LIST}
  events:
    - http:
        path: api/usuarios/{id}
        method: get
        cors: true
        request:
          parameters:
            paths:
              id: true
